<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $recipes = [

            // --- Nepali (Dal Bhat family) ---
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Nepali Dal Bhat',
                'description' => 'Traditional Nepali dish with rice, lentils, and vegetables.',
                'preparation_time' => '60',
                'cooking_time' => '45',
                'servings' => 5,
                'ingredients' => json_encode(['Rice', 'Lentils', 'Spinach', 'Potatoes', 'Spices']),
                'instructions' => json_encode(['Cook rice and lentils.', 'Prepare vegetable curry.', 'Serve with pickles.']),
                'images' => 'uploads/nepali-dal-bhat.jpg',
                'is_approved' => true,
                'view_count' => 50,
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Dal Bhat Tarkari',
                'description' => 'Rice, lentils and mixed vegetable curry.',
                'preparation_time' => '55',
                'cooking_time' => '40',
                'servings' => 4,
                'ingredients' => json_encode(['Rice', 'Lentils', 'Carrots', 'Cauliflower', 'Spices']),
                'instructions' => json_encode(['Cook rice.', 'Prepare lentil soup.', 'Cook tarkari with spices.']),
                'images' => 'uploads/dal-bhat-tarkari.jpg',
                'is_approved' => true,
                'view_count' => 42,
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Mutton Curry Dal Bhat',
                'description' => 'Rice with lentils and spicy mutton curry.',
                'preparation_time' => '70',
                'cooking_time' => '60',
                'servings' => 6,
                'ingredients' => json_encode(['Rice', 'Lentils', 'Mutton', 'Onions', 'Garlic', 'Spices']),
                'instructions' => json_encode(['Cook rice and lentils.', 'Prepare spicy mutton curry.', 'Serve together.']),
                'images' => 'uploads/mutton-dal-bhat.jpg',
                'is_approved' => true,
                'view_count' => 48,
            ],
            [
                'user_id' => 1,
                'category_id' => 1,
                'name' => 'Vegetarian Dal Bhat',
                'description' => 'Rice, lentils and seasonal vegetables.',
                'preparation_time' => '50',
                'cooking_time' => '40',
                'servings' => 4,
                'ingredients' => json_encode(['Rice', 'Lentils', 'Green beans', 'Spinach', 'Potatoes']),
                'instructions' => json_encode(['Cook rice.', 'Prepare dal.', 'Cook vegetable curry.']),
                'images' => 'uploads/veg-dal-bhat.jpg',
                'is_approved' => true,
                'view_count' => 39,
            ],

            // --- Indian (Curry family) ---
            [
                'user_id' => 1,
                'category_id' => 8,
                'name' => 'Butter Chicken',
                'description' => 'Creamy and spiced chicken curry.',
                'preparation_time' => '45',
                'cooking_time' => '35',
                'servings' => 4,
                'ingredients' => json_encode(['Chicken', 'Butter', 'Tomato sauce', 'Cream', 'Spices']),
                'instructions' => json_encode(['Marinate chicken.', 'Cook with butter and spices.', 'Add sauce and cream.']),
                'images' => 'uploads/butter-chicken.jpg',
                'is_approved' => true,
                'view_count' => 35,
            ],
            [
                'user_id' => 1,
                'category_id' => 8,
                'name' => 'Chicken Tikka Masala',
                'description' => 'Grilled chicken in a spicy tomato-based sauce.',
                'preparation_time' => '60',
                'cooking_time' => '40',
                'servings' => 4,
                'ingredients' => json_encode(['Chicken', 'Yogurt', 'Tomato puree', 'Onions', 'Spices']),
                'instructions' => json_encode(['Marinate chicken.', 'Grill.', 'Cook in masala sauce.']),
                'images' => 'uploads/chicken-tikka-masala.jpg',
                'is_approved' => true,
                'view_count' => 38,
            ],
            [
                'user_id' => 1,
                'category_id' => 8,
                'name' => 'Paneer Butter Masala',
                'description' => 'Creamy curry made with paneer cubes.',
                'preparation_time' => '40',
                'cooking_time' => '30',
                'servings' => 3,
                'ingredients' => json_encode(['Paneer', 'Butter', 'Tomato sauce', 'Cream', 'Spices']),
                'instructions' => json_encode(['Fry paneer.', 'Cook with butter and spices.', 'Add sauce and cream.']),
                'images' => 'uploads/paneer-butter-masala.jpg',
                'is_approved' => true,
                'view_count' => 33,
            ],
            [
                'user_id' => 1,
                'category_id' => 8,
                'name' => 'Chana Masala',
                'description' => 'Chickpeas cooked in spicy tomato gravy.',
                'preparation_time' => '35',
                'cooking_time' => '25',
                'servings' => 3,
                'ingredients' => json_encode(['Chickpeas', 'Tomatoes', 'Onions', 'Garlic', 'Spices']),
                'instructions' => json_encode(['Boil chickpeas.', 'Cook with masala.', 'Simmer and serve.']),
                'images' => 'uploads/chana-masala.jpg',
                'is_approved' => true,
                'view_count' => 29,
            ],

            // --- Chinese (Dumpling/Stir-fry family) ---
            [
                'user_id' => 1,
                'category_id' => 2,
                'name' => 'Vegetable Stir Fry',
                'description' => 'Quick and healthy stir-fried vegetables.',
                'preparation_time' => '15',
                'cooking_time' => '10',
                'servings' => 3,
                'ingredients' => json_encode(['Broccoli', 'Bell peppers', 'Carrots', 'Soy sauce']),
                'instructions' => json_encode(['Chop vegetables.', 'Stir fry in soy sauce.']),
                'images' => 'uploads/veg-stir-fry.jpg',
                'is_approved' => true,
                'view_count' => 18,
            ],
            [
                'user_id' => 1,
                'category_id' => 2,
                'name' => 'Chicken Stir Fry',
                'description' => 'Chicken with fresh vegetables in soy sauce.',
                'preparation_time' => '20',
                'cooking_time' => '15',
                'servings' => 3,
                'ingredients' => json_encode(['Chicken', 'Broccoli', 'Bell peppers', 'Soy sauce']),
                'instructions' => json_encode(['Cook chicken.', 'Stir fry vegetables.', 'Combine with soy sauce.']),
                'images' => 'uploads/chicken-stir-fry.jpg',
                'is_approved' => true,
                'view_count' => 20,
            ],
            [
                'user_id' => 1,
                'category_id' => 2,
                'name' => 'Chinese Dumplings',
                'description' => 'Steamed dumplings with pork and vegetables.',
                'preparation_time' => '50',
                'cooking_time' => '20',
                'servings' => 6,
                'ingredients' => json_encode(['Dumpling wrappers', 'Ground pork', 'Cabbage', 'Ginger', 'Soy sauce']),
                'instructions' => json_encode(['Prepare filling.', 'Wrap dumplings.', 'Steam 20 minutes.']),
                'images' => 'uploads/chinese-dumplings.jpg',
                'is_approved' => true,
                'view_count' => 28,
            ],
            [
                'user_id' => 1,
                'category_id' => 2,
                'name' => 'Veg Dumplings',
                'description' => 'Steamed dumplings with vegetables.',
                'preparation_time' => '45',
                'cooking_time' => '20',
                'servings' => 6,
                'ingredients' => json_encode(['Dumpling wrappers', 'Cabbage', 'Carrots', 'Onions', 'Soy sauce']),
                'instructions' => json_encode(['Prepare veg filling.', 'Wrap dumplings.', 'Steam until cooked.']),
                'images' => 'uploads/veg-dumplings.jpg',
                'is_approved' => true,
                'view_count' => 25,
            ],

            // --- Japanese (Sushi/Noodle family) ---
            [
                'user_id' => 1,
                'category_id' => 5,
                'name' => 'Sushi Rolls',
                'description' => 'Fresh sushi rolls with rice and vegetables.',
                'preparation_time' => '50',
                'cooking_time' => '0',
                'servings' => 2,
                'ingredients' => json_encode(['Sushi rice', 'Nori sheets', 'Avocado', 'Cucumber']),
                'instructions' => json_encode(['Cook rice.', 'Place rice on nori.', 'Roll with fillings.']),
                'images' => 'uploads/sushi-rolls.jpg',
                'is_approved' => true,
                'view_count' => 40,
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'name' => 'Salmon Nigiri',
                'description' => 'Rice topped with fresh salmon.',
                'preparation_time' => '30',
                'cooking_time' => '0',
                'servings' => 2,
                'ingredients' => json_encode(['Sushi rice', 'Salmon', 'Wasabi']),
                'instructions' => json_encode(['Shape rice.', 'Top with salmon.', 'Serve with wasabi.']),
                'images' => 'uploads/salmon-nigiri.jpg',
                'is_approved' => true,
                'view_count' => 35,
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'name' => 'Tuna Sushi Roll',
                'description' => 'Sushi rolls filled with tuna and cucumber.',
                'preparation_time' => '45',
                'cooking_time' => '0',
                'servings' => 2,
                'ingredients' => json_encode(['Sushi rice', 'Nori', 'Tuna', 'Cucumber']),
                'instructions' => json_encode(['Place rice on nori.', 'Add tuna and cucumber.', 'Roll tightly.']),
                'images' => 'uploads/tuna-sushi-roll.jpg',
                'is_approved' => true,
                'view_count' => 33,
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'name' => 'Japanese Ramen',
                'description' => 'Noodle soup with broth and toppings.',
                'preparation_time' => '60',
                'cooking_time' => '30',
                'servings' => 2,
                'ingredients' => json_encode(['Ramen noodles', 'Broth', 'Egg', 'Pork', 'Seaweed']),
                'instructions' => json_encode(['Prepare broth.', 'Cook noodles.', 'Add toppings.']),
                'images' => 'uploads/japanese-ramen.jpg',
                'is_approved' => true,
                'view_count' => 38,
            ],

            // --- Thai (Noodle family) ---
            [
                'user_id' => 1,
                'category_id' => 3,
                'name' => 'Spicy Thai Noodles',
                'description' => 'Noodles with spicy peanut sauce.',
                'preparation_time' => '20',
                'cooking_time' => '15',
                'servings' => 4,
                'ingredients' => json_encode(['Rice noodles', 'Peanut butter', 'Soy sauce', 'Chili flakes']),
                'instructions' => json_encode(['Cook noodles.', 'Mix peanut sauce.', 'Combine and serve.']),
                'images' => 'uploads/spicy-thai-noodles.jpg',
                'is_approved' => true,
                'view_count' => 15,
            ],
            [
                'user_id' => 1,
                'category_id' => 3,
                'name' => 'Pad Thai',
                'description' => 'Classic Thai stir-fried noodles.',
                'preparation_time' => '25',
                'cooking_time' => '15',
                'servings' => 3,
                'ingredients' => json_encode(['Rice noodles', 'Egg', 'Shrimp', 'Peanuts', 'Bean sprouts']),
                'instructions' => json_encode(['Cook noodles.', 'Stir fry with egg and shrimp.', 'Garnish with peanuts.']),
                'images' => 'uploads/pad-thai.jpg',
                'is_approved' => true,
                'view_count' => 22,
            ],
            [
                'user_id' => 1,
                'category_id' => 3,
                'name' => 'Thai Green Curry',
                'description' => 'Spicy green curry with chicken.',
                'preparation_time' => '40',
                'cooking_time' => '25',
                'servings' => 3,
                'ingredients' => json_encode(['Chicken', 'Green curry paste', 'Coconut milk', 'Vegetables']),
                'instructions' => json_encode(['Cook curry paste.', 'Add chicken.', 'Pour coconut milk and simmer.']),
                'images' => 'uploads/thai-green-curry.jpg',
                'is_approved' => true,
                'view_count' => 28,
            ],
            [
                'user_id' => 1,
                'category_id' => 3,
                'name' => 'Thai Red Curry',
                'description' => 'Spicy red curry with chicken and vegetables.',
                'preparation_time' => '40',
                'cooking_time' => '25',
                'servings' => 3,
                'ingredients' => json_encode(['Chicken', 'Red curry paste', 'Coconut milk', 'Vegetables']),
                'instructions' => json_encode(['Cook curry paste.', 'Add chicken.', 'Add coconut milk.', 'Simmer.']),
                'images' => 'uploads/thai-red-curry.jpg',
                'is_approved' => true,
                'view_count' => 30,
            ],

            // --- Korean (BBQ family) ---
            [
                'user_id' => 1,
                'category_id' => 4,
                'name' => 'Korean BBQ Beef',
                'description' => 'Grilled marinated beef slices.',
                'preparation_time' => '40',
                'cooking_time' => '20',
                'servings' => 3,
                'ingredients' => json_encode(['Beef', 'Soy sauce', 'Garlic', 'Sesame oil']),
                'instructions' => json_encode(['Marinate beef.', 'Grill until cooked.']),
                'images' => 'uploads/korean-bbq-beef.jpg',
                'is_approved' => true,
                'view_count' => 26,
            ],
            [
                'user_id' => 1,
                'category_id' => 4,
                'name' => 'Korean Bulgogi',
                'description' => 'Sweet-savory marinated beef.',
                'preparation_time' => '35',
                'cooking_time' => '20',
                'servings' => 3,
                'ingredients' => json_encode(['Beef', 'Soy sauce', 'Sugar', 'Garlic', 'Onions']),
                'instructions' => json_encode(['Slice beef thin.', 'Marinate with sauce.', 'Grill quickly.']),
                'images' => 'uploads/korean-bulgogi.jpg',
                'is_approved' => true,
                'view_count' => 29,
            ],
            [
                'user_id' => 1,
                'category_id' => 4,
                'name' => 'Korean Kimchi Stew',
                'description' => 'Spicy stew made with kimchi.',
                'preparation_time' => '30',
                'cooking_time' => '25',
                'servings' => 3,
                'ingredients' => json_encode(['Kimchi', 'Pork', 'Tofu', 'Garlic']),
                'instructions' => json_encode(['Cook pork.', 'Add kimchi.', 'Simmer with tofu.']),
                'images' => 'uploads/kimchi-stew.jpg',
                'is_approved' => true,
                'view_count' => 21,
            ],
            [
                'user_id' => 1,
                'category_id' => 4,
                'name' => 'Bibimbap',
                'description' => 'Mixed rice bowl with vegetables and egg.',
                'preparation_time' => '30',
                'cooking_time' => '15',
                'servings' => 2,
                'ingredients' => json_encode(['Rice', 'Carrots', 'Spinach', 'Egg', 'Gochujang']),
                'instructions' => json_encode(['Cook rice.', 'Stir fry vegetables.', 'Assemble bowl with toppings.']),
                'images' => 'uploads/bibimbap.jpg',
                'is_approved' => true,
                'view_count' => 23,
            ],

            // --- Italian (Pizza family) ---
            [
                'user_id' => 1,
                'category_id' => 7,
                'name' => 'Margherita Pizza',
                'description' => 'Classic pizza with basil and mozzarella.',
                'preparation_time' => '20',
                'cooking_time' => '20',
                'servings' => 2,
                'ingredients' => json_encode(['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Basil']),
                'instructions' => json_encode(['Roll dough.', 'Spread sauce.', 'Add toppings.', 'Bake.']),
                'images' => 'uploads/margherita-pizza.jpg',
                'is_approved' => true,
                'view_count' => 22,
            ],
            [
                'user_id' => 1,
                'category_id' => 7,
                'name' => 'Pepperoni Pizza',
                'description' => 'Pizza topped with spicy pepperoni.',
                'preparation_time' => '25',
                'cooking_time' => '18',
                'servings' => 3,
                'ingredients' => json_encode(['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Pepperoni']),
                'instructions' => json_encode(['Roll dough.', 'Spread sauce.', 'Add cheese and pepperoni.', 'Bake.']),
                'images' => 'uploads/pepperoni-pizza.jpg',
                'is_approved' => true,
                'view_count' => 27,
            ],
            [
                'user_id' => 1,
                'category_id' => 7,
                'name' => 'Four Cheese Pizza',
                'description' => 'Pizza with mozzarella, parmesan, cheddar, and gorgonzola.',
                'preparation_time' => '30',
                'cooking_time' => '20',
                'servings' => 2,
                'ingredients' => json_encode(['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Cheddar', 'Parmesan', 'Gorgonzola']),
                'instructions' => json_encode(['Roll dough.', 'Add sauce and cheese.', 'Bake.']),
                'images' => 'uploads/four-cheese-pizza.jpg',
                'is_approved' => true,
                'view_count' => 31,
            ],
            [
                'user_id' => 1,
                'category_id' => 7,
                'name' => 'Veggie Pizza',
                'description' => 'Pizza with assorted vegetables.',
                'preparation_time' => '30',
                'cooking_time' => '20',
                'servings' => 2,
                'ingredients' => json_encode(['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Bell peppers', 'Onions', 'Olives']),
                'instructions' => json_encode(['Roll dough.', 'Add sauce and toppings.', 'Bake.']),
                'images' => 'uploads/veggie-pizza.jpg',
                'is_approved' => true,
                'view_count' => 28,
            ],
        ];

        foreach ($recipes as $recipe) {
            Recipe::create($recipe);
        }
    }
}
